version: "3.8"

services:
  # Heydesk Backend API
  heydesk-api:
    build:
      context: ./Heydesk.Server
      dockerfile: Dockerfile
    container_name: heydesk-api
    restart: unless-stopped
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    env_file:
      - ./Heydesk.Server/.env
    volumes:
      - ./Heydesk.Server/https:/https:ro
